#!/usr/bin/env python3                                                                                               

import sys
import argparse
from math import *

if (len(sys.argv) != 2):
        exit (84)
if sys.argv[1] == "-h":
    print("uSAGE\n\t./109titration file\n\nDESCRIPTION\n\tfile    a csv file containing “vol;ph” lines")
    exit (0)
try :
    fd = open(sys.argv[1], "r")
except :
    exit (84)
tab = fd.readlines()
d_tab = []
loop = 1
sol = 0
eq = 0
point  = 0
v1 = 0
v2 = 0

for i in range (len(tab)):
    tab[i] = tab[i].strip('\n').split(';')
    tab[i][0] = float(tab[i][0])
    tab[i][1] = float(tab[i][1])

d_tab.append(0)
print("Derivative:")
for loop in range (1, len(tab) - 1):
    d_tab.append(((tab[loop + 1][1]) - (tab[loop - 1][1])) / ((tab[loop + 1][0]) - (tab[loop - 1][0])))
    print("%.1f ml -> %.2f"%(tab[loop][0], d_tab[loop]))
    if (eq < d_tab[loop]):
        sol = tab[loop][0]
        check = loop
        eq = d_tab[loop]

print("\nEquivalent point at %.1f ml\n\nSecond derivative:"%sol)
d_tab.append(0)

for loop in range (1, len(tab) - 3):
    point = (((d_tab[loop + 2]) - (d_tab[loop])) / ((tab[loop + 2][0]) - (tab[loop][0])))
    print("%.1f ml -> %.2f"%(tab[loop + 1][0], point))
    if (eq < d_tab[loop]):
        sol = tab[loop][0]
        check = loop
        eq = d_tab[loop]

