##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile infinAdd
##

SRC     =       201yams

all:
		    chmod +x $(SRC)

clean:
			rm -f *.o
			rm -f *~

fclean:
			rm -f $(NAME)

re:     	fclean all
