#!/usr/bin/env python3
import sys
import math

def main():
    if (len(sys.argv) < 2 or len(sys.argv) > 4):
        exit (84)
    if sys.argv[1] == "-h":
        print("USAGE\n\t./106bombyx n [k | i0 i1]\n\nDESCRIPTION\n    n    number of first generation indivifuals\n    k    growth rate from 1 to 4\n    i0   initial generation (included) i1    final generation (included)")
        exit (0)
    if (len(sys.argv) == 3):
        try :
            n = int(sys.argv[1])
            k = float(sys.argv[2])
        except :
            exit (84)
        first(n, k)
    elif (len(sys.argv) == 4):
        second()

def first(n, k):
    compte = 1
    for loop in range (100):
        print(compte,"%0.*f" %(2, n), sep=' ')
        n = haineplushun(n,k)
        compte += 1

def second():
    try :
        f = int(sys.argv[3])
        i = int(sys.argv[2])
        n = int(sys.argv[1])
    except :
        exit (84)
    k = 1.00
    while (k <= 4.00):
        for loop in range (f+1):
            n = haineplushun(n,k)
            if (loop >= i):
                print("%.2f" %k,"%0.*f" %(2, n), sep=' ')
        k += 0.01
        if (k == 4):
            exit (0)

def haineplushun(n,k):
    return (k*n*((1000-n)/1000))

main()
